# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title unbalanced barycenter
#'@description Compute the entropic unbalanced wasserstein barycenter of A.
#'
#'@param A matrix(dim, n). n training distributions a_i of dimension dim.
#'@param M matrix(dim, dim). ground metric matrix for OT.
#'@param weighs vector(n). Weight of each distribution (barycentric coodinates).
#'@param reg Entropy regularization term > 0.
#'@param reg_m Marginal relaxation term > 0.
#'@param numItermax int. Max number of iterations.
#'@param stopThr float. Stop threshol on error (> 0).
#'@param verbose bool. Print information along iterations.
#'
#'@return vector(dim). Unbalanced Wasserstein barycenter
#'
#'@examples
#'a=dnorm(1:100,20,10)
#'a=a/sum(a)
#'b=dnorm(1:100, mean=60, sd=2)
#'b=b/sum(b)*2
#'dab = matrix(c(a, b), 100, 2)
#'distance= dists(1:100,1:100)
#'distance = distance/max(distance)
#'res = barycenter_unbalanced_stabilized(dab, distance, reg = 1, reg_m = 1, weights = c(0.5, 0.5))
#'p = data.frame(ind = 1:100, a = a, b = b, c = res)
#'ggplot(data = p)+geom_line(aes(x = ind, y = a), color = "blue")+
#'geom_line(aes(x = ind, y = b), color = "red")+
#'geom_line(aes(x = ind, y = res), color = "green")
#'
#'@references
#'[1] Benamou, J. D., Carlier, G., Cuturi, M., Nenna, L., & Peyre, G.(2015). Iterative Bregman projections for regularized transportation problems. SIAM Journal on Scientific Computing, 37(2), A1111-A1138.
#'[2] Chizat, L., Peyre, G., Schmitzer, B., & Vialard, F. X. (2016). Scaling algorithms for unbalanced transport problems. arXiv preprin arXiv:1607.05816.
#'
barycenter_unbalanced_stabilized <- function(A, M, weights, reg = 0.1, reg_m = 1, numItermax = 1000L, stopThr = 1e-8, verbose = FALSE) {
    .Call('_ROT_barycenter_unbalanced_stabilized', PACKAGE = 'ROT', A, M, weights, reg, reg_m, numItermax, stopThr, verbose)
}

#' @title distance between two samples(dimension=1)
#' @description Compute the distance matrix between samples of one dimention.
#' @param a sample a
#' @param b sample b
#' @param k the order of the norm (default k=1)
#' @return the kth power of the k-norm of the distance between a and b
#' @examples
#' distance=dists(1:100,1:100)
dists <- function(a, b, k = 1L, dimention = 1L) {
    .Call('_ROT_dists', PACKAGE = 'ROT', a, b, k, dimention)
}

#' @title distance between two samples(dimension>1)
#' @description Compute the distance matrix between two samples (dimensions>1)
#' @param a mat a(n,p) n:the number of samples,p:the dimensionnality
#' @param b mat b(n,p) n:the number of samples,p:the dimensionnality
#' @param k the order of the norm of the distance (default k=1)
#' @return the k-norm of the distance between a and b
#' @examples
#' a = cbind(1:10,1:10)
#' dist_mat(a,a)
dist_mat <- function(a, b, k = 1L, square = 0L) {
    .Call('_ROT_dist_mat', PACKAGE = 'ROT', a, b, k, square)
}

#'@title computer the transport plan of partial optimal transport
#'@param a the the vector of source distribution
#'@param b the vector of target dirtribution 
#'@param mat the cost matrix
#'@param reg entropic regularization parameter
#'@param numItemax the max iteration times
#'@param stopThr ending condition
#'@examples
#'a<-c(0.4,0.8)
#'b<-c(0.6,3)
#' m1<-c(0,1)
#' m2<-c(1,0)
#' m<-cbind(m1,m2)
#' pat_uot(a,b,m,1)
pat_uot <- function(a, b, dab, reg, numItemax = 1000L, stopThr = 1e-20) {
    .Call('_ROT_pat_uot', PACKAGE = 'ROT', a, b, dab, reg, numItemax, stopThr)
}

#'@title computer the wasserstein distance  of partial optimal transport
#'@param a the the vector of source distribution
#'@param b the vector of target dirtribution 
#'@param mat the cost matrix
#'@param reg entropic regularization parameter
#'@examples
#'a<-c(0.4,0.8)
#'b<-c(0.6,3)
#' m1<-c(0,1)
#' m2<-c(1,0)
#' m<-cbind(m1,m2)
#' pat_uot_was(a,b,m,1)
pat_uot_was <- function(a, b, dab, reg) {
    .Call('_ROT_pat_uot_was', PACKAGE = 'ROT', a, b, dab, reg)
}

#'@title computer the plan of regularized unbalanced optimal transport
#'@description Solve the entropic regularization unbalanced optimal transport
#'@param a vec a is the the histogram of source distribution(dim_a=m)
#'@param b vec b is the histogram of target dirtribution (dim_b=n)
#'@param dab matrix dab is the cost matrix between a and b
#'@param reg entropic regularization parameter
#'@param reg_m marginal relaxation term > 0
#'@param numItemax the max iteration times
#'@param stopThr ending condition
#'@return a matrix that shape:m
#'@examples
#'a<-c(0.4,0.8)
#'b<-c(0.6,3)
#' m1<-c(0,1)
#' m2<-c(1,0)
#' m<-cbind(m1,m2)
#' sinkhorn_knopp_unbalanced(a,b,m,1,1)
sinkhorn_knopp_unbalanced <- function(a, b, dab, reg, reg_m, numItermax = 100L, stopThr = 1e-6) {
    .Call('_ROT_sinkhorn_knopp_unbalanced', PACKAGE = 'ROT', a, b, dab, reg, reg_m, numItermax, stopThr)
}

#'@title sinkhorn unbalanced OT distance
#'@description Solve the entropic regularization unbalanced optimal transport problem and return the loss.
#'
#'@param a vector(dim_a). Unnormalized histogram of dimension dim_a.
#'@param b vector(dim_b). Unnormalized histogram of dimension dim_b.
#'@param dab matrix(dim_a, dim_b). loss matrix.
#'@param reg float. Entropy regularization term > 0.
#'@param reg_m float. Marginal relaxation term > 0.
#'
#'@return the OT distance between `a` and 'b`
#'
#'@examples
#'a<-c(0.4,0.8)
#'b<-c(0.6,3)
#'m1<-c(0,1)
#'m2<-c(1,0)
#'m<-cbind(m1,m2)
#'sinkhorn_knopp_unbalanced_was(a,b,m,1,1)
#'
#'@references
#'[1] Chizat, L., Peyre, G., Schmitzer, B., & Vialard, F. X. (2016). Scaling algorithms for unbalanced transport problems. arXiv preprint arXiv:1607.05816.
#'[2] Frogner C., Zhang C., Mobahi H., Araya-Polo M., Poggio T. Learning with a Wasserstein Loss,  Advances in Neural Information Processing Systems (NIPS) 2015.
sinkhorn_knopp_unbalanced_was <- function(a, b, dab, reg, reg_m) {
    .Call('_ROT_sinkhorn_knopp_unbalanced_was', PACKAGE = 'ROT', a, b, dab, reg, reg_m)
}

#'@title computer the plan of regularized unbalanced optimal transport
#'@description Solve the entropic regularization unbalanced optimal transport
#'@param a vec a is the the histogram of source distribution(dim_a=m)
#'@param b vec b is the histogram of target dirtribution (dim_b=n)
#'@param dab matrix dab is the cost matrix between a and b
#'@param reg entropic regularization parameter
#'@param reg_m marginal relaxation term > 0
#'@param numItemax the max iteration times
#'@param stopThr ending condition
#'@return a matrix that shape:m
#'@examples
#'a<-c(0.4,0.8)
#'b<-c(0.6,3)
#' m1<-c(0,1)
#' m2<-c(1,0)
#' m<-cbind(m1,m2)
#' sinkhorn_stabilized(a,b,m,1,1)
sinkhorn_stabilized <- function(a, b, dab, reg, reg_m, tau = 1e5, numltermax = 1000L, stopThr = 1e-6) {
    .Call('_ROT_sinkhorn_stabilized', PACKAGE = 'ROT', a, b, dab, reg, reg_m, tau, numltermax, stopThr)
}

#'@title sinkhorn unbalanced OT distance
#'@description Solve the entropic regularization unbalanced optimal transport problem and return the loss.
#'
#'@param a vector(dim_a). Unnormalized histogram of dimension dim_a.
#'@param b vector(dim_b). Unnormalized histogram of dimension dim_b.
#'@param dab matrix(dim_a, dim_b). loss matrix.
#'@param reg float. Entropy regularization term > 0.
#'@param reg_m float. Marginal relaxation term > 0.
#'
#'@return the OT distance between `a` and 'b`
#'
#'@examples
#'a<-c(0.4,0.8)
#'b<-c(0.6,3)
#'m1<-c(0,1)
#'m2<-c(1,0)
#'m<-cbind(m1,m2)
#'sinkhorn_stabilized_was(a,b,m,1,1)
#'
#'@references
#'[1] Chizat, L., Peyre, G., Schmitzer, B., & Vialard, F. X. (2016). Scaling algorithms for unbalanced transport problems. arXiv preprint arXiv:1607.05816.
#'[2] Frogner C., Zhang C., Mobahi H., Araya-Polo M., Poggio T. Learning with a Wasserstein Loss,  Advances in Neural Information Processing Systems (NIPS) 2015.
sinkhorn_stabilized_was <- function(a, b, dab, reg, reg_m) {
    .Call('_ROT_sinkhorn_stabilized_was', PACKAGE = 'ROT', a, b, dab, reg, reg_m)
}

